# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01787fe2866cdca285fbd42728d3a54d7cda5181ccfd43c158600ab55b778fcbcba655a51bdaf4d920218e6e541f40bde3841bb8b0712d455b6c0d0184bb789f

test:
  secret_key_base: 6b386cba7f83293588794b4c6e9571fca3dd47c226a8a015b5b51f1bb654ae4e4a590e5ded9c604ff1b2607ab98b4118867b4edbc356807b9f4bf66b3678bba8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
